# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WFGui_2015_02_17.ui'
#
# Created: Tue Feb 17 11:56:24 2015
#      by: PySide UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(376, 742)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_Axes.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_15 = QtGui.QGridLayout(Form)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -35, 340, 722))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget_0 = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget_0.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_0.setObjectName(_fromUtf8("tabWidget_0"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tabWidget = QtGui.QTabWidget(self.tab_2)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Origin_Tab = QtGui.QWidget()
        self.Origin_Tab.setObjectName(_fromUtf8("Origin_Tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Origin_Tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.button_origin = QtGui.QPushButton(self.Origin_Tab)
        self.button_origin.setIcon(icon)
        self.button_origin.setIconSize(QtCore.QSize(32, 32))
        self.button_origin.setObjectName(_fromUtf8("button_origin"))
        self.verticalLayout_3.addWidget(self.button_origin)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Origin_Tab, icon, _fromUtf8(""))
        self.Point_Tab = QtGui.QWidget()
        self.Point_Tab.setObjectName(_fromUtf8("Point_Tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Point_Tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.button_object_center = QtGui.QPushButton(self.Point_Tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerObjectsPoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_object_center.setIcon(icon1)
        self.button_object_center.setIconSize(QtCore.QSize(32, 32))
        self.button_object_center.setObjectName(_fromUtf8("button_object_center"))
        self.horizontalLayout_10.addWidget(self.button_object_center)
        self.checkBox_object_center = QtGui.QCheckBox(self.Point_Tab)
        self.checkBox_object_center.setObjectName(_fromUtf8("checkBox_object_center"))
        self.horizontalLayout_10.addWidget(self.checkBox_object_center)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.button_Npoints_center = QtGui.QPushButton(self.Point_Tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_NpointsPoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Npoints_center.setIcon(icon2)
        self.button_Npoints_center.setIconSize(QtCore.QSize(32, 32))
        self.button_Npoints_center.setObjectName(_fromUtf8("button_Npoints_center"))
        self.gridLayout_3.addWidget(self.button_Npoints_center, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.button_line_center = QtGui.QPushButton(self.Point_Tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerLinePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_line_center.setIcon(icon3)
        self.button_line_center.setIconSize(QtCore.QSize(32, 32))
        self.button_line_center.setObjectName(_fromUtf8("button_line_center"))
        self.horizontalLayout_6.addWidget(self.button_line_center)
        self.spin_line_center = QtGui.QSpinBox(self.Point_Tab)
        self.spin_line_center.setMinimumSize(QtCore.QSize(40, 0))
        self.spin_line_center.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spin_line_center.setMinimum(2)
        self.spin_line_center.setMaximum(10)
        self.spin_line_center.setSingleStep(1)
        self.spin_line_center.setObjectName(_fromUtf8("spin_line_center"))
        self.horizontalLayout_6.addWidget(self.spin_line_center)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.button_line_extrema = QtGui.QPushButton(self.Point_Tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_extremaLinePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_line_extrema.setIcon(icon4)
        self.button_line_extrema.setIconSize(QtCore.QSize(32, 32))
        self.button_line_extrema.setObjectName(_fromUtf8("button_line_extrema"))
        self.gridLayout_3.addWidget(self.button_line_extrema, 3, 0, 1, 1)
        self.button_circle_center = QtGui.QPushButton(self.Point_Tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerCirclePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_circle_center.setIcon(icon5)
        self.button_circle_center.setIconSize(QtCore.QSize(32, 32))
        self.button_circle_center.setObjectName(_fromUtf8("button_circle_center"))
        self.gridLayout_3.addWidget(self.button_circle_center, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_point_on_line = QtGui.QPushButton(self.Point_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_point_on_line.sizePolicy().hasHeightForWidth())
        self.button_point_on_line.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_alongLinePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_point_on_line.setIcon(icon6)
        self.button_point_on_line.setIconSize(QtCore.QSize(32, 32))
        self.button_point_on_line.setObjectName(_fromUtf8("button_point_on_line"))
        self.horizontalLayout.addWidget(self.button_point_on_line)
        self.distance_point_on_line = QtGui.QLineEdit(self.Point_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_point_on_line.sizePolicy().hasHeightForWidth())
        self.distance_point_on_line.setSizePolicy(sizePolicy)
        self.distance_point_on_line.setMinimumSize(QtCore.QSize(50, 0))
        self.distance_point_on_line.setMaximumSize(QtCore.QSize(60, 16777215))
        self.distance_point_on_line.setObjectName(_fromUtf8("distance_point_on_line"))
        self.horizontalLayout.addWidget(self.distance_point_on_line)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.button_face_center = QtGui.QPushButton(self.Point_Tab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerFacePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_face_center.setIcon(icon7)
        self.button_face_center.setIconSize(QtCore.QSize(32, 32))
        self.button_face_center.setObjectName(_fromUtf8("button_face_center"))
        self.gridLayout_3.addWidget(self.button_face_center, 6, 0, 1, 1)
        self.button_line_face_point = QtGui.QPushButton(self.Point_Tab)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_lineFacePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_line_face_point.setIcon(icon8)
        self.button_line_face_point.setIconSize(QtCore.QSize(32, 32))
        self.button_line_face_point.setObjectName(_fromUtf8("button_line_face_point"))
        self.gridLayout_3.addWidget(self.button_line_face_point, 7, 0, 1, 1)
        self.button_point_line_point = QtGui.QPushButton(self.Point_Tab)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_pointLinePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_point_line_point.setIcon(icon9)
        self.button_point_line_point.setIconSize(QtCore.QSize(32, 32))
        self.button_point_line_point.setObjectName(_fromUtf8("button_point_line_point"))
        self.gridLayout_3.addWidget(self.button_point_line_point, 8, 0, 1, 1)
        self.button_point_face_point = QtGui.QPushButton(self.Point_Tab)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_pointFacePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_point_face_point.setIcon(icon10)
        self.button_point_face_point.setIconSize(QtCore.QSize(32, 32))
        self.button_point_face_point.setObjectName(_fromUtf8("button_point_face_point"))
        self.gridLayout_3.addWidget(self.button_point_face_point, 9, 0, 1, 1)
        self.button_twolines_point = QtGui.QPushButton(self.Point_Tab)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_lineLinePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_twolines_point.setIcon(icon11)
        self.button_twolines_point.setIconSize(QtCore.QSize(32, 32))
        self.button_twolines_point.setObjectName(_fromUtf8("button_twolines_point"))
        self.gridLayout_3.addWidget(self.button_twolines_point, 10, 0, 1, 1)
        self.button_click_for_point = QtGui.QPushButton(self.Point_Tab)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_clickPoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_click_for_point.setIcon(icon12)
        self.button_click_for_point.setIconSize(QtCore.QSize(32, 32))
        self.button_click_for_point.setCheckable(False)
        self.button_click_for_point.setObjectName(_fromUtf8("button_click_for_point"))
        self.gridLayout_3.addWidget(self.button_click_for_point, 11, 0, 1, 1)
        self.button_object_base_point = QtGui.QPushButton(self.Point_Tab)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_objectBasePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_object_base_point.setIcon(icon13)
        self.button_object_base_point.setIconSize(QtCore.QSize(32, 32))
        self.button_object_base_point.setObjectName(_fromUtf8("button_object_base_point"))
        self.gridLayout_3.addWidget(self.button_object_base_point, 12, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 13, 0, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_point.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Point_Tab, icon14, _fromUtf8(""))
        self.Axis_Tab = QtGui.QWidget()
        self.Axis_Tab.setObjectName(_fromUtf8("Axis_Tab"))
        self.gridLayout = QtGui.QGridLayout(self.Axis_Tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.button_twopoints_axis = QtGui.QPushButton(self.Axis_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_twopoints_axis.sizePolicy().hasHeightForWidth())
        self.button_twopoints_axis.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_2pointsLine.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_twopoints_axis.setIcon(icon15)
        self.button_twopoints_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_twopoints_axis.setObjectName(_fromUtf8("button_twopoints_axis"))
        self.horizontalLayout_2.addWidget(self.button_twopoints_axis)
        self.extension_twopoints_axis = QtGui.QLineEdit(self.Axis_Tab)
        self.extension_twopoints_axis.setMaximumSize(QtCore.QSize(60, 16777215))
        self.extension_twopoints_axis.setObjectName(_fromUtf8("extension_twopoints_axis"))
        self.horizontalLayout_2.addWidget(self.extension_twopoints_axis)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.button_cylinder_axis = QtGui.QPushButton(self.Axis_Tab)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_cylinderAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cylinder_axis.setIcon(icon16)
        self.button_cylinder_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_cylinder_axis.setObjectName(_fromUtf8("button_cylinder_axis"))
        self.gridLayout.addWidget(self.button_cylinder_axis, 2, 0, 1, 1)
        self.button_object_base_axes = QtGui.QPushButton(self.Axis_Tab)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_baseObjectsAxes.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_object_base_axes.setIcon(icon17)
        self.button_object_base_axes.setIconSize(QtCore.QSize(32, 32))
        self.button_object_base_axes.setObjectName(_fromUtf8("button_object_base_axes"))
        self.gridLayout.addWidget(self.button_object_base_axes, 11, 0, 1, 1)
        self.button_point_line_axis = QtGui.QPushButton(self.Axis_Tab)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_pointLineAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_point_line_axis.setIcon(icon18)
        self.button_point_line_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_point_line_axis.setObjectName(_fromUtf8("button_point_line_axis"))
        self.gridLayout.addWidget(self.button_point_line_axis, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.button_line_point_axis = QtGui.QPushButton(self.Axis_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_line_point_axis.sizePolicy().hasHeightForWidth())
        self.button_line_point_axis.setSizePolicy(sizePolicy)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_linePointAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_line_point_axis.setIcon(icon19)
        self.button_line_point_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_line_point_axis.setObjectName(_fromUtf8("button_line_point_axis"))
        self.horizontalLayout_7.addWidget(self.button_line_point_axis)
        self.extension_line_point_axis = QtGui.QLineEdit(self.Axis_Tab)
        self.extension_line_point_axis.setMaximumSize(QtCore.QSize(60, 16777215))
        self.extension_line_point_axis.setObjectName(_fromUtf8("extension_line_point_axis"))
        self.horizontalLayout_7.addWidget(self.extension_line_point_axis)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.button_face_normal = QtGui.QPushButton(self.Axis_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_face_normal.sizePolicy().hasHeightForWidth())
        self.button_face_normal.setSizePolicy(sizePolicy)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_FaceNormal.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_face_normal.setIcon(icon20)
        self.button_face_normal.setIconSize(QtCore.QSize(32, 32))
        self.button_face_normal.setObjectName(_fromUtf8("button_face_normal"))
        self.horizontalLayout_5.addWidget(self.button_face_normal)
        self.extension_face_normal = QtGui.QLineEdit(self.Axis_Tab)
        self.extension_face_normal.setMinimumSize(QtCore.QSize(40, 0))
        self.extension_face_normal.setMaximumSize(QtCore.QSize(60, 16777215))
        self.extension_face_normal.setObjectName(_fromUtf8("extension_face_normal"))
        self.horizontalLayout_5.addWidget(self.extension_face_normal)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.button_twolines_axis = QtGui.QPushButton(self.Axis_Tab)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_twoLinesAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_twolines_axis.setIcon(icon21)
        self.button_twolines_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_twolines_axis.setObjectName(_fromUtf8("button_twolines_axis"))
        self.gridLayout.addWidget(self.button_twolines_axis, 3, 0, 1, 1)
        self.button_object_axis = QtGui.QPushButton(self.Axis_Tab)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerObjectsAxes.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_object_axis.setIcon(icon22)
        self.button_object_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_object_axis.setObjectName(_fromUtf8("button_object_axis"))
        self.gridLayout.addWidget(self.button_object_axis, 0, 0, 1, 1)
        self.button_twoplanes_axis = QtGui.QPushButton(self.Axis_Tab)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_2PlanesAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_twoplanes_axis.setIcon(icon23)
        self.button_twoplanes_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_twoplanes_axis.setObjectName(_fromUtf8("button_twoplanes_axis"))
        self.gridLayout.addWidget(self.button_twoplanes_axis, 9, 0, 1, 1)
        self.button_plane_axis = QtGui.QPushButton(self.Axis_Tab)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_FaceAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plane_axis.setIcon(icon24)
        self.button_plane_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_plane_axis.setObjectName(_fromUtf8("button_plane_axis"))
        self.gridLayout.addWidget(self.button_plane_axis, 4, 0, 1, 1)
        self.button_line_plane_axis = QtGui.QPushButton(self.Axis_Tab)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_linePlaneAxis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_line_plane_axis.setIcon(icon25)
        self.button_line_plane_axis.setIconSize(QtCore.QSize(32, 32))
        self.button_line_plane_axis.setObjectName(_fromUtf8("button_line_plane_axis"))
        self.gridLayout.addWidget(self.button_line_plane_axis, 8, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_axis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Axis_Tab, icon26, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.button_3points_circle = QtGui.QPushButton(self.tab_4)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_3pointsCircle.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_3points_circle.setIcon(icon27)
        self.button_3points_circle.setIconSize(QtCore.QSize(32, 32))
        self.button_3points_circle.setObjectName(_fromUtf8("button_3points_circle"))
        self.gridLayout_5.addWidget(self.button_3points_circle, 2, 0, 1, 1)
        self.button_3points_ellipse = QtGui.QPushButton(self.tab_4)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_3pointsEllipse.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_3points_ellipse.setIcon(icon28)
        self.button_3points_ellipse.setIconSize(QtCore.QSize(32, 32))
        self.button_3points_ellipse.setObjectName(_fromUtf8("button_3points_ellipse"))
        self.gridLayout_5.addWidget(self.button_3points_ellipse, 3, 0, 1, 1)
        self.button_linepoint_circle = QtGui.QPushButton(self.tab_4)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_linePointCircle.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_linepoint_circle.setIcon(icon29)
        self.button_linepoint_circle.setIconSize(QtCore.QSize(32, 32))
        self.button_linepoint_circle.setObjectName(_fromUtf8("button_linepoint_circle"))
        self.gridLayout_5.addWidget(self.button_linepoint_circle, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.button_linecenter_circle = QtGui.QPushButton(self.tab_4)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_lineCenterCircle.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_linecenter_circle.setIcon(icon30)
        self.button_linecenter_circle.setIconSize(QtCore.QSize(32, 32))
        self.button_linecenter_circle.setObjectName(_fromUtf8("button_linecenter_circle"))
        self.horizontalLayout_11.addWidget(self.button_linecenter_circle)
        self.radius_circle = QtGui.QLineEdit(self.tab_4)
        self.radius_circle.setMinimumSize(QtCore.QSize(40, 0))
        self.radius_circle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radius_circle.setObjectName(_fromUtf8("radius_circle"))
        self.horizontalLayout_11.addWidget(self.radius_circle)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 4, 0, 1, 1)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_circle.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon31, _fromUtf8(""))
        self.Plane_Tab = QtGui.QWidget()
        self.Plane_Tab.setObjectName(_fromUtf8("Plane_Tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.Plane_Tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.button_planeandpoint_plane = QtGui.QPushButton(self.Plane_Tab)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_pointPlanePoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_planeandpoint_plane.setIcon(icon32)
        self.button_planeandpoint_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_planeandpoint_plane.setObjectName(_fromUtf8("button_planeandpoint_plane"))
        self.gridLayout_16.addWidget(self.button_planeandpoint_plane, 0, 0, 1, 1)
        self.extension_planePointPlane = QtGui.QLineEdit(self.Plane_Tab)
        self.extension_planePointPlane.setMinimumSize(QtCore.QSize(40, 0))
        self.extension_planePointPlane.setMaximumSize(QtCore.QSize(60, 16777215))
        self.extension_planePointPlane.setObjectName(_fromUtf8("extension_planePointPlane"))
        self.gridLayout_16.addWidget(self.extension_planePointPlane, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_16, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 6, 0, 1, 1)
        self.button_axis_point_plane = QtGui.QPushButton(self.Plane_Tab)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_linePointPlane2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_axis_point_plane.setIcon(icon33)
        self.button_axis_point_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_axis_point_plane.setObjectName(_fromUtf8("button_axis_point_plane"))
        self.gridLayout_9.addWidget(self.button_axis_point_plane, 2, 0, 1, 1)
        self.button_object_center_planes = QtGui.QPushButton(self.Plane_Tab)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_centerObjectsPlanes.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_object_center_planes.setIcon(icon34)
        self.button_object_center_planes.setIconSize(QtCore.QSize(32, 32))
        self.button_object_center_planes.setObjectName(_fromUtf8("button_object_center_planes"))
        self.gridLayout_9.addWidget(self.button_object_center_planes, 9, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.button_planeandaxis_plane = QtGui.QPushButton(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_planeandaxis_plane.sizePolicy().hasHeightForWidth())
        self.button_planeandaxis_plane.setSizePolicy(sizePolicy)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_planeLinePlane.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_planeandaxis_plane.setIcon(icon35)
        self.button_planeandaxis_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_planeandaxis_plane.setObjectName(_fromUtf8("button_planeandaxis_plane"))
        self.gridLayout_8.addWidget(self.button_planeandaxis_plane, 0, 0, 1, 1)
        self.angle_planeandaxis_plane = QtGui.QLineEdit(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_planeandaxis_plane.sizePolicy().hasHeightForWidth())
        self.angle_planeandaxis_plane.setSizePolicy(sizePolicy)
        self.angle_planeandaxis_plane.setMinimumSize(QtCore.QSize(40, 0))
        self.angle_planeandaxis_plane.setMaximumSize(QtCore.QSize(60, 16777215))
        self.angle_planeandaxis_plane.setObjectName(_fromUtf8("angle_planeandaxis_plane"))
        self.gridLayout_8.addWidget(self.angle_planeandaxis_plane, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 4, 0, 1, 1)
        self.button_axisandpoint_plane = QtGui.QPushButton(self.Plane_Tab)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_linePointPlane.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_axisandpoint_plane.setIcon(icon36)
        self.button_axisandpoint_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_axisandpoint_plane.setObjectName(_fromUtf8("button_axisandpoint_plane"))
        self.gridLayout_9.addWidget(self.button_axisandpoint_plane, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.button_click_for_plane = QtGui.QPushButton(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_click_for_plane.sizePolicy().hasHeightForWidth())
        self.button_click_for_plane.setSizePolicy(sizePolicy)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_clickPlane.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_click_for_plane.setIcon(icon37)
        self.button_click_for_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_click_for_plane.setObjectName(_fromUtf8("button_click_for_plane"))
        self.horizontalLayout_3.addWidget(self.button_click_for_plane)
        self.length_plane = QtGui.QLineEdit(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_plane.sizePolicy().hasHeightForWidth())
        self.length_plane.setSizePolicy(sizePolicy)
        self.length_plane.setMinimumSize(QtCore.QSize(40, 0))
        self.length_plane.setMaximumSize(QtCore.QSize(60, 16777215))
        self.length_plane.setObjectName(_fromUtf8("length_plane"))
        self.horizontalLayout_3.addWidget(self.length_plane)
        self.width_plane = QtGui.QLineEdit(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_plane.sizePolicy().hasHeightForWidth())
        self.width_plane.setSizePolicy(sizePolicy)
        self.width_plane.setMinimumSize(QtCore.QSize(40, 0))
        self.width_plane.setMaximumSize(QtCore.QSize(60, 16777215))
        self.width_plane.setObjectName(_fromUtf8("width_plane"))
        self.horizontalLayout_3.addWidget(self.width_plane)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.button_face_tangent = QtGui.QPushButton(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_face_tangent.sizePolicy().hasHeightForWidth())
        self.button_face_tangent.setSizePolicy(sizePolicy)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_FaceTangent.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_face_tangent.setIcon(icon38)
        self.button_face_tangent.setIconSize(QtCore.QSize(32, 32))
        self.button_face_tangent.setObjectName(_fromUtf8("button_face_tangent"))
        self.horizontalLayout_12.addWidget(self.button_face_tangent)
        self.length_plane_2 = QtGui.QLineEdit(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_plane_2.sizePolicy().hasHeightForWidth())
        self.length_plane_2.setSizePolicy(sizePolicy)
        self.length_plane_2.setMinimumSize(QtCore.QSize(40, 0))
        self.length_plane_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.length_plane_2.setObjectName(_fromUtf8("length_plane_2"))
        self.horizontalLayout_12.addWidget(self.length_plane_2)
        self.width_plane_2 = QtGui.QLineEdit(self.Plane_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_plane_2.sizePolicy().hasHeightForWidth())
        self.width_plane_2.setSizePolicy(sizePolicy)
        self.width_plane_2.setMinimumSize(QtCore.QSize(40, 0))
        self.width_plane_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.width_plane_2.setObjectName(_fromUtf8("width_plane_2"))
        self.horizontalLayout_12.addWidget(self.width_plane_2)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.button_threepoints_plane = QtGui.QPushButton(self.Plane_Tab)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_threePointsPlane.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_threepoints_plane.setIcon(icon39)
        self.button_threepoints_plane.setIconSize(QtCore.QSize(32, 32))
        self.button_threepoints_plane.setObjectName(_fromUtf8("button_threepoints_plane"))
        self.gridLayout_9.addWidget(self.button_threepoints_plane, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 8, 0, 1, 1)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_plane.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Plane_Tab, icon40, _fromUtf8(""))
        self.Objects_Tab2 = QtGui.QWidget()
        self.Objects_Tab2.setEnabled(True)
        self.Objects_Tab2.setMinimumSize(QtCore.QSize(0, 0))
        self.Objects_Tab2.setObjectName(_fromUtf8("Objects_Tab2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.Objects_Tab2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.button_cylinder_create = QtGui.QPushButton(self.Objects_Tab2)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_cylinder.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cylinder_create.setIcon(icon41)
        self.button_cylinder_create.setIconSize(QtCore.QSize(32, 32))
        self.button_cylinder_create.setObjectName(_fromUtf8("button_cylinder_create"))
        self.gridLayout_6.addWidget(self.button_cylinder_create, 0, 0, 1, 1)
        self.diameter_cylinder = QtGui.QLineEdit(self.Objects_Tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter_cylinder.sizePolicy().hasHeightForWidth())
        self.diameter_cylinder.setSizePolicy(sizePolicy)
        self.diameter_cylinder.setMinimumSize(QtCore.QSize(50, 0))
        self.diameter_cylinder.setMaximumSize(QtCore.QSize(60, 16777215))
        self.diameter_cylinder.setObjectName(_fromUtf8("diameter_cylinder"))
        self.gridLayout_6.addWidget(self.diameter_cylinder, 0, 1, 1, 1)
        self.length_cylinder = QtGui.QLineEdit(self.Objects_Tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_cylinder.sizePolicy().hasHeightForWidth())
        self.length_cylinder.setSizePolicy(sizePolicy)
        self.length_cylinder.setMinimumSize(QtCore.QSize(50, 0))
        self.length_cylinder.setMaximumSize(QtCore.QSize(60, 16777215))
        self.length_cylinder.setObjectName(_fromUtf8("length_cylinder"))
        self.gridLayout_6.addWidget(self.length_cylinder, 0, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.button_cube_create = QtGui.QPushButton(self.Objects_Tab2)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_cube.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cube_create.setIcon(icon42)
        self.button_cube_create.setIconSize(QtCore.QSize(32, 32))
        self.button_cube_create.setObjectName(_fromUtf8("button_cube_create"))
        self.horizontalLayout_4.addWidget(self.button_cube_create)
        self.section_cube = QtGui.QLineEdit(self.Objects_Tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section_cube.sizePolicy().hasHeightForWidth())
        self.section_cube.setSizePolicy(sizePolicy)
        self.section_cube.setMinimumSize(QtCore.QSize(50, 0))
        self.section_cube.setMaximumSize(QtCore.QSize(60, 16777215))
        self.section_cube.setObjectName(_fromUtf8("section_cube"))
        self.horizontalLayout_4.addWidget(self.section_cube)
        self.height_cube = QtGui.QLineEdit(self.Objects_Tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_cube.sizePolicy().hasHeightForWidth())
        self.height_cube.setSizePolicy(sizePolicy)
        self.height_cube.setMinimumSize(QtCore.QSize(50, 0))
        self.height_cube.setMaximumSize(QtCore.QSize(60, 16777215))
        self.height_cube.setObjectName(_fromUtf8("height_cube"))
        self.horizontalLayout_4.addWidget(self.height_cube)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.button_boundingboxes = QtGui.QPushButton(self.Objects_Tab2)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_boundingBoxes.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_boundingboxes.setIcon(icon43)
        self.button_boundingboxes.setIconSize(QtCore.QSize(32, 32))
        self.button_boundingboxes.setObjectName(_fromUtf8("button_boundingboxes"))
        self.gridLayout_12.addWidget(self.button_boundingboxes, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 5, 0, 1, 1)
        self.button_boundingbox = QtGui.QPushButton(self.Objects_Tab2)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_boundingBox.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_boundingbox.setIcon(icon44)
        self.button_boundingbox.setIconSize(QtCore.QSize(32, 32))
        self.button_boundingbox.setObjectName(_fromUtf8("button_boundingbox"))
        self.gridLayout_12.addWidget(self.button_boundingbox, 1, 0, 1, 1)
        self.line = QtGui.QFrame(self.Objects_Tab2)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_12.addWidget(self.line, 2, 0, 1, 1)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_box.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Objects_Tab2, icon45, _fromUtf8(""))
        self.View_Tab = QtGui.QWidget()
        self.View_Tab.setObjectName(_fromUtf8("View_Tab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.View_Tab)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.button_alignview = QtGui.QPushButton(self.View_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_alignview.sizePolicy().hasHeightForWidth())
        self.button_alignview.setSizePolicy(sizePolicy)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_viewAlign.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_alignview.setIcon(icon46)
        self.button_alignview.setIconSize(QtCore.QSize(32, 32))
        self.button_alignview.setObjectName(_fromUtf8("button_alignview"))
        self.gridLayout_13.addWidget(self.button_alignview, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem7, 1, 0, 1, 1)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(_fromUtf8("icons:WF_view.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.View_Tab, icon47, _fromUtf8(""))
        self.Modif_Tab = QtGui.QWidget()
        self.Modif_Tab.setObjectName(_fromUtf8("Modif_Tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.Modif_Tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tabWidget_2 = QtGui.QTabWidget(self.Modif_Tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_angle = QtGui.QLabel(self.tab_5)
        self.label_angle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_angle.setObjectName(_fromUtf8("label_angle"))
        self.gridLayout_19.addWidget(self.label_angle, 0, 0, 1, 1)
        self.angle_cut_object = QtGui.QLineEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_cut_object.sizePolicy().hasHeightForWidth())
        self.angle_cut_object.setSizePolicy(sizePolicy)
        self.angle_cut_object.setMinimumSize(QtCore.QSize(0, 0))
        self.angle_cut_object.setMaximumSize(QtCore.QSize(50, 16777215))
        self.angle_cut_object.setObjectName(_fromUtf8("angle_cut_object"))
        self.gridLayout_19.addWidget(self.angle_cut_object, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_thickness = QtGui.QLabel(self.tab_5)
        self.label_thickness.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_thickness.setObjectName(_fromUtf8("label_thickness"))
        self.gridLayout_20.addWidget(self.label_thickness, 0, 0, 1, 1)
        self.thickness_cut_object = QtGui.QLineEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thickness_cut_object.sizePolicy().hasHeightForWidth())
        self.thickness_cut_object.setSizePolicy(sizePolicy)
        self.thickness_cut_object.setMaximumSize(QtCore.QSize(50, 16777215))
        self.thickness_cut_object.setObjectName(_fromUtf8("thickness_cut_object"))
        self.gridLayout_20.addWidget(self.thickness_cut_object, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_20, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.button_cut_reset = QtGui.QPushButton(self.tab_5)
        self.button_cut_reset.setMinimumSize(QtCore.QSize(40, 0))
        self.button_cut_reset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_cut_reset.setObjectName(_fromUtf8("button_cut_reset"))
        self.horizontalLayout_8.addWidget(self.button_cut_reset)
        spacerItem8 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.button_cut_apply = QtGui.QPushButton(self.tab_5)
        self.button_cut_apply.setEnabled(False)
        self.button_cut_apply.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_cut_apply.setIconSize(QtCore.QSize(32, 32))
        self.button_cut_apply.setObjectName(_fromUtf8("button_cut_apply"))
        self.horizontalLayout_8.addWidget(self.button_cut_apply)
        self.gridLayout_17.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.button_cut_select_object = QtGui.QPushButton(self.tab_5)
        self.button_cut_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.button_cut_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.button_cut_select_object.setObjectName(_fromUtf8("button_cut_select_object"))
        self.gridLayout_18.addWidget(self.button_cut_select_object, 0, 0, 1, 1)
        self.info_cut_select_object = QtGui.QLineEdit(self.tab_5)
        self.info_cut_select_object.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_cut_select_object.sizePolicy().hasHeightForWidth())
        self.info_cut_select_object.setSizePolicy(sizePolicy)
        self.info_cut_select_object.setReadOnly(True)
        self.info_cut_select_object.setObjectName(_fromUtf8("info_cut_select_object"))
        self.gridLayout_18.addWidget(self.info_cut_select_object, 1, 0, 1, 1)
        self.button_cut_select_line = QtGui.QPushButton(self.tab_5)
        self.button_cut_select_line.setEnabled(False)
        self.button_cut_select_line.setMinimumSize(QtCore.QSize(130, 31))
        self.button_cut_select_line.setMaximumSize(QtCore.QSize(250, 40))
        self.button_cut_select_line.setObjectName(_fromUtf8("button_cut_select_line"))
        self.gridLayout_18.addWidget(self.button_cut_select_line, 2, 0, 1, 1)
        self.info_cut_select_axis = QtGui.QLineEdit(self.tab_5)
        self.info_cut_select_axis.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_cut_select_axis.sizePolicy().hasHeightForWidth())
        self.info_cut_select_axis.setSizePolicy(sizePolicy)
        self.info_cut_select_axis.setReadOnly(True)
        self.info_cut_select_axis.setObjectName(_fromUtf8("info_cut_select_axis"))
        self.gridLayout_18.addWidget(self.info_cut_select_axis, 3, 0, 1, 1)
        self.button_cut_select_plane = QtGui.QPushButton(self.tab_5)
        self.button_cut_select_plane.setEnabled(False)
        self.button_cut_select_plane.setMinimumSize(QtCore.QSize(130, 31))
        self.button_cut_select_plane.setMaximumSize(QtCore.QSize(250, 40))
        self.button_cut_select_plane.setObjectName(_fromUtf8("button_cut_select_plane"))
        self.gridLayout_18.addWidget(self.button_cut_select_plane, 4, 0, 1, 1)
        self.info_cut_select_plane = QtGui.QLineEdit(self.tab_5)
        self.info_cut_select_plane.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_cut_select_plane.sizePolicy().hasHeightForWidth())
        self.info_cut_select_plane.setSizePolicy(sizePolicy)
        self.info_cut_select_plane.setReadOnly(True)
        self.info_cut_select_plane.setObjectName(_fromUtf8("info_cut_select_plane"))
        self.gridLayout_18.addWidget(self.info_cut_select_plane, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Modif_Tab, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget_0.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.radioButton_verbose = QtGui.QRadioButton(self.tab_3)
        self.radioButton_verbose.setObjectName(_fromUtf8("radioButton_verbose"))
        self.gridLayout_14.addWidget(self.radioButton_verbose, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem10, 1, 0, 1, 1)
        self.tabWidget_0.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget_0, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_15.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.button_WF_quit = QtGui.QPushButton(Form)
        self.button_WF_quit.setObjectName(_fromUtf8("button_WF_quit"))
        self.horizontalLayout_9.addWidget(self.button_WF_quit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.label_release = QtGui.QLabel(Form)
        self.label_release.setObjectName(_fromUtf8("label_release"))
        self.horizontalLayout_9.addWidget(self.label_release)
        self.gridLayout_15.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_0.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "WorkFeature", None, QtGui.QApplication.UnicodeUTF8))
        self.button_origin.setToolTip(QtGui.QApplication.translate("Form", "Create at origin: a point and X,Y and Z axis and XZ,XY  and YZ planes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_origin.setText(QtGui.QApplication.translate("Form", "Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Origin_Tab), QtGui.QApplication.translate("Form", "Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_center.setToolTip(QtGui.QApplication.translate("Form", "Create a Point at center location of all selected Object(s).\n"
"    if BBox is not toggled\n"
"        This point is the MEAN location of all center of Mass (if exist) of all objects.\n"
"        All  center of Mass will be created too.\n"
"    if BBox is toggled\n"
"        This point is the center of the Global X,Y,Z bounding box of all objects.\n"
"        This bounding box alway exists (especially for draft objects).\n"
"        Be aware this point is not necessary the center of Mass of all Objects!", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_center.setText(QtGui.QApplication.translate("Form", "Object(s) Center", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_object_center.setText(QtGui.QApplication.translate("Form", "BBox", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Npoints_center.setToolTip(QtGui.QApplication.translate("Form", "Create a Point at mean location of all selected points.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Npoints_center.setText(QtGui.QApplication.translate("Form", "Points Center", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_center.setToolTip(QtGui.QApplication.translate("Form", "Create Point(s):\n"
"Cut each selected Lines(s) in 2 (n) parts and create a (n-1) Point(s) at ends of edge(s).\n"
"The number indicates how many  parts to consider.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_center.setText(QtGui.QApplication.translate("Form", "Line(s) Center", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_line_center.setToolTip(QtGui.QApplication.translate("Form", "The number indicates in how many  parts each selected Lines(s) will be cut.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_extrema.setToolTip(QtGui.QApplication.translate("Form", "Create Points at start and end location of each selected Line(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_extrema.setText(QtGui.QApplication.translate("Form", "Line(s) Extrema", None, QtGui.QApplication.UnicodeUTF8))
        self.button_circle_center.setToolTip(QtGui.QApplication.translate("Form", "Create a Point at center location of each selected Circle(s) or Arc(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_circle_center.setText(QtGui.QApplication.translate("Form", "Circle(s) Center", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_on_line.setToolTip(QtGui.QApplication.translate("Form", "Create a Point at a certain distance along the line \n"
"respecting to the choosen reference starting point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_on_line.setText(QtGui.QApplication.translate("Form", "Point along Line", None, QtGui.QApplication.UnicodeUTF8))
        self.distance_point_on_line.setToolTip(QtGui.QApplication.translate("Form", "Distance from the extremity", None, QtGui.QApplication.UnicodeUTF8))
        self.distance_point_on_line.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_center.setToolTip(QtGui.QApplication.translate("Form", "Create a Point at center location of each selected Face(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_center.setText(QtGui.QApplication.translate("Form", "Face(s) Center", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_face_point.setToolTip(QtGui.QApplication.translate("Form", "Create a point at the intersection of the Line and Plane selected.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_face_point.setText(QtGui.QApplication.translate("Form", "Point=(Line,Face) ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_line_point.setToolTip(QtGui.QApplication.translate("Form", "Create a projection Point of a Point onto a Line and symetric point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_line_point.setText(QtGui.QApplication.translate("Form", "Point=(Line,Point) ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_face_point.setToolTip(QtGui.QApplication.translate("Form", "Create a projection Point of a Point onto a Face.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_face_point.setText(QtGui.QApplication.translate("Form", "Point=(Point,Face)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twolines_point.setToolTip(QtGui.QApplication.translate("Form", "Plot one or two Point(s) at minimum distance of two Lines\n"
"Create a Point at intersection of 2 crossing Lines.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twolines_point.setText(QtGui.QApplication.translate("Form", "Point=(Line,Line) ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_click_for_point.setToolTip(QtGui.QApplication.translate("Form", "Create a Point on a Plane perpendicular to the view at location of one mouse click.\n"
"Click first on the Button then click once on the View (with no object in background).\n"
"Click first on the Button then click once on the View (with an object in background) will attach the point to the surface of the object.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.button_click_for_point.setText(QtGui.QApplication.translate("Form", "Click", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_base_point.setToolTip(QtGui.QApplication.translate("Form", "Create Base Point of all selected Object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_base_point.setText(QtGui.QApplication.translate("Form", "Object(s) Base Point", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Point_Tab), QtGui.QApplication.translate("Form", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twopoints_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis crossing 2 Points.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twopoints_axis.setText(QtGui.QApplication.translate("Form", "Two Points Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_twopoints_axis.setToolTip(QtGui.QApplication.translate("Form", "Distance for the extensions on extrema", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_twopoints_axis.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cylinder_axis.setToolTip(QtGui.QApplication.translate("Form", "Create the Axis of a Cylinder.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cylinder_axis.setText(QtGui.QApplication.translate("Form", "Cylinder(s) Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_base_axes.setToolTip(QtGui.QApplication.translate("Form", "Create 3 Axes at Base location of all selected Object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_base_axes.setText(QtGui.QApplication.translate("Form", "Object(s) Base Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_line_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis parallel to an Axis and crossing a Point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_point_line_axis.setText(QtGui.QApplication.translate("Form", "Axis=(Point,Axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_point_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis perpendicular to an Axis and crossing a Point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_point_axis.setText(QtGui.QApplication.translate("Form", "Axis=(Axis,Point)", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_line_point_axis.setToolTip(QtGui.QApplication.translate("Form", "Distance for the extensions on extrema.", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_line_point_axis.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_normal.setToolTip(QtGui.QApplication.translate("Form", "Create a normal Axis at click location of a Face.\n"
"Click first in the view to select and object,\n"
"then push the button, \n"
"then click on a location on the selected object.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_normal.setText(QtGui.QApplication.translate("Form", "Face Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_face_normal.setToolTip(QtGui.QApplication.translate("Form", "Length of Normal Axis.", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_face_normal.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twolines_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis between 2 Axes.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twolines_axis.setText(QtGui.QApplication.translate("Form", "Axis=(Line,Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_axis.setToolTip(QtGui.QApplication.translate("Form", "Create 3 Axes at center location of all selected Object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_axis.setText(QtGui.QApplication.translate("Form", "Object(s) X, Y, Z Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twoplanes_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis by intersect of 2 Planes.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_twoplanes_axis.setText(QtGui.QApplication.translate("Form", "Axis=(Plane,Plane)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_plane_axis.setToolTip(QtGui.QApplication.translate("Form", "Create 2 Perpendicular Axes at center location of a Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_plane_axis.setText(QtGui.QApplication.translate("Form", "Plane(s) Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_plane_axis.setToolTip(QtGui.QApplication.translate("Form", "Create an Axis on a Plane by projection from anoher Axis.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line_plane_axis.setText(QtGui.QApplication.translate("Form", "Axis=(Plane,Axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Axis_Tab), QtGui.QApplication.translate("Form", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3points_circle.setToolTip(QtGui.QApplication.translate("Form", "Select 3 Points  to create a Circle.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3points_circle.setText(QtGui.QApplication.translate("Form", "Circle=(3 points)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3points_ellipse.setToolTip(QtGui.QApplication.translate("Form", "Select a center and 2 Points to create an Ellipse.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3points_ellipse.setText(QtGui.QApplication.translate("Form", "Ellipse=(3 points)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_linepoint_circle.setToolTip(QtGui.QApplication.translate("Form", "Select an Axis and a Point  to create a Circle\n"
"centered on the Axis and tangenting the Point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_linepoint_circle.setText(QtGui.QApplication.translate("Form", "Circle=(Axis, point)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_linecenter_circle.setToolTip(QtGui.QApplication.translate("Form", "Select an Axis and a Point to create a Circle\n"
"centered on the Point, perpendicular to the Axis \n"
"with the given radius.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_linecenter_circle.setText(QtGui.QApplication.translate("Form", "Circle=(Axis, center)", None, QtGui.QApplication.UnicodeUTF8))
        self.radius_circle.setToolTip(QtGui.QApplication.translate("Form", "Radius of the Circle.", None, QtGui.QApplication.UnicodeUTF8))
        self.radius_circle.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.button_planeandpoint_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a plane crossing a Point and parallel to a Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_planeandpoint_plane.setText(QtGui.QApplication.translate("Form", "Plane=(Point, Plane)", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_planePointPlane.setToolTip(QtGui.QApplication.translate("Form", "Distance for the extensions of the new Plane compared to initial one.", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_planePointPlane.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_axis_point_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a plane perpendicular to a Line and crossing a Point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_axis_point_plane.setText(QtGui.QApplication.translate("Form", "Plane=(Point, _|Axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_center_planes.setToolTip(QtGui.QApplication.translate("Form", "Create 3 Planes (XY, XZ and YZ) at center location of all selected Object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_object_center_planes.setText(QtGui.QApplication.translate("Form", "Object(s) Center Planes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_planeandaxis_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a Plane crossing a Line and perpendicular to a Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_planeandaxis_plane.setText(QtGui.QApplication.translate("Form", "Plane=(Plane, Axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_planeandaxis_plane.setToolTip(QtGui.QApplication.translate("Form", "Angle relative to the Plane (in degrees).", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_planeandaxis_plane.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_axisandpoint_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a plane crossing a Line and a Point.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_axisandpoint_plane.setText(QtGui.QApplication.translate("Form", "Plane=(Point, Axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_click_for_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a Plane perpendicular to the view at location of one mouse click.\n"
"Click first on the Button then click once on the View.\n"
"Click first on the Button then click once on one object of the View\n"
" to attach the plane at the object.\n"
"But you can also select an already existing point first and click the button to attach the plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_click_for_plane.setText(QtGui.QApplication.translate("Form", "Click", None, QtGui.QApplication.UnicodeUTF8))
        self.length_plane.setToolTip(QtGui.QApplication.translate("Form", "Length of the Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.length_plane.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.width_plane.setToolTip(QtGui.QApplication.translate("Form", "Width of the Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.width_plane.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_tangent.setToolTip(QtGui.QApplication.translate("Form", "Create a tanget Plane at click location of a Face.\n"
"Click first in the view to select and object,\n"
"then push the button, \n"
"then click on a location on the selected object.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_face_tangent.setText(QtGui.QApplication.translate("Form", "Face Tangent", None, QtGui.QApplication.UnicodeUTF8))
        self.length_plane_2.setToolTip(QtGui.QApplication.translate("Form", "Length of the Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.length_plane_2.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.width_plane_2.setToolTip(QtGui.QApplication.translate("Form", "Width of the Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.width_plane_2.setText(QtGui.QApplication.translate("Form", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_threepoints_plane.setToolTip(QtGui.QApplication.translate("Form", "Create a Plane crossing 3 Points.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_threepoints_plane.setText(QtGui.QApplication.translate("Form", "Three Points Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Plane_Tab), QtGui.QApplication.translate("Form", "Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cylinder_create.setToolTip(QtGui.QApplication.translate("Form", "First select an Axis and a Point. \n"
"Define Diameter and Length if needed.\n"
"Then Click the button...\n"
"It will create a Cylinder aligned on the selected axis \n"
"with one of the extremities at point selected.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cylinder_create.setText(QtGui.QApplication.translate("Form", "Cylinder", None, QtGui.QApplication.UnicodeUTF8))
        self.diameter_cylinder.setToolTip(QtGui.QApplication.translate("Form", "Diameter of the Cylinder.", None, QtGui.QApplication.UnicodeUTF8))
        self.diameter_cylinder.setText(QtGui.QApplication.translate("Form", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.length_cylinder.setToolTip(QtGui.QApplication.translate("Form", "Length of the Cylinder.", None, QtGui.QApplication.UnicodeUTF8))
        self.length_cylinder.setText(QtGui.QApplication.translate("Form", "20.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cube_create.setToolTip(QtGui.QApplication.translate("Form", "First select an Axis and a Point. \n"
"Define Dimensions if needed.\n"
"Then Click the button...\n"
"It will create a Cube aligned on the selected axis \n"
"with one of the extremities at point selected.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cube_create.setText(QtGui.QApplication.translate("Form", "Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.section_cube.setToolTip(QtGui.QApplication.translate("Form", "Section (Length, Width) of the Cube.", None, QtGui.QApplication.UnicodeUTF8))
        self.section_cube.setText(QtGui.QApplication.translate("Form", "2.0,2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.height_cube.setToolTip(QtGui.QApplication.translate("Form", "Heigth of the Cube.", None, QtGui.QApplication.UnicodeUTF8))
        self.height_cube.setText(QtGui.QApplication.translate("Form", "20.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_boundingboxes.setToolTip(QtGui.QApplication.translate("Form", "Create bounding boxes around each of selected object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_boundingboxes.setText(QtGui.QApplication.translate("Form", "Bounding Box(es)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_boundingbox.setToolTip(QtGui.QApplication.translate("Form", "Create one bounding box around all of selected object(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.button_boundingbox.setText(QtGui.QApplication.translate("Form", "Bounding Box", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Objects_Tab2), QtGui.QApplication.translate("Form", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.button_alignview.setToolTip(QtGui.QApplication.translate("Form", "Set the current view perpendicular to the selected Face, \n"
"or aligned to the selected Axis, \n"
"or aligned on 2 Points.\n"
"ReClick with same selection, will reverse the direction.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_alignview.setText(QtGui.QApplication.translate("Form", "Align to ...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.View_Tab), QtGui.QApplication.translate("Form", "Views", None, QtGui.QApplication.UnicodeUTF8))
        self.label_angle.setText(QtGui.QApplication.translate("Form", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_cut_object.setToolTip(QtGui.QApplication.translate("Form", "Angle of cutting  relative to the Reference Plane (in degrees).", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_cut_object.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_thickness.setText(QtGui.QApplication.translate("Form", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness_cut_object.setToolTip(QtGui.QApplication.translate("Form", "Thickness of the Cut.", None, QtGui.QApplication.UnicodeUTF8))
        self.thickness_cut_object.setText(QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_reset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_apply.setToolTip(QtGui.QApplication.translate("Form", "Cut an object by selecting a Line cut, a Plane and an Angle regarding the Plane.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_apply.setText(QtGui.QApplication.translate("Form", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_object.setToolTip(QtGui.QApplication.translate("Form", "Select the Object to cut:\n"
"First Click on the object in the view \n"
"and push this button to accept...", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_object.setText(QtGui.QApplication.translate("Form", "Select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_line.setToolTip(QtGui.QApplication.translate("Form", "Select the Line to cut the Object along:\n"
"First Click on the line/edge in the view \n"
"and push this button to accept...", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_line.setText(QtGui.QApplication.translate("Form", "Select Cut Line", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_plane.setToolTip(QtGui.QApplication.translate("Form", "Select the reference Plane to cut the Object from:\n"
"First Click on the plane in the view \n"
"and push this button to accept...\n"
"(Note that the Angle is calculated from this Plane)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cut_select_plane.setText(QtGui.QApplication.translate("Form", "Select Ref. Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Cutting", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Modif_Tab), QtGui.QApplication.translate("Form", "Modif.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_0.setTabText(self.tabWidget_0.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "W. F.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_verbose.setToolTip(QtGui.QApplication.translate("Form", "Toggle here if you want a lot of information printed into report View.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_verbose.setText(QtGui.QApplication.translate("Form", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_0.setTabText(self.tabWidget_0.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Pref.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_WF_quit.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_release.setText(QtGui.QApplication.translate("Form", "2015", None, QtGui.QApplication.UnicodeUTF8))

